name: "cache"

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  nix-build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - channel: nixos-24.11
        - channel: nixpkgs-unstable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          allow-import-from-derivation = false
          keep-going = true
          show-trace = true
        nix_path: nixpkgs=channel:${{ matrix.channel }}
    - uses: cachix/cachix-action@v16
      with:
        name: hmenke
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: "(-source$|nixpkgs.tar.gz$)"
    - name: Run nix build
      run: nix build --print-build-logs --no-link --file ./default.nix
    - name: Prepare artifacts
      if: ${{ matrix.channel == 'nixos-24.11' }}
      run: |
        nix build --file ./default.nix -o .local local-bin
        tar cvf local-bin.tar --mode='u+rwX,go+rX' --dereference .local/bin/*
        tar cvf local-libexec.tar --mode='u+rwX,go+rX' .local/libexec/git-core/*
        gzip -fv --rsyncable local-bin.tar
        gzip -fv --rsyncable local-libexec.tar
    - uses: actions/upload-artifact@v4
      if: ${{ matrix.channel == 'nixos-24.11' }}
      with:
        path: |
          local-bin.tar.gz
          local-libexec.tar.gz
