name: "cache"

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: "allow-import-from-derivation = false"
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: hmenke
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: "(-source$|nixpkgs.tar.gz$)"
    - name: Run nix-build
      run: nix-build --show-trace --no-out-link
    - name: Prepare artifacts
      run: |
        nix-build --show-trace -A local-bin -o local-bin
        tar czvf local-bin.tar.gz --mode='a+rwX' local-bin/*
    - uses: actions/upload-artifact@v3
      with:
        name: local-bin
        path: local-bin.tar.gz
