name: "cache"

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v24
      with:
        extra_nix_config: "allow-import-from-derivation = false"
        nix_path: nixpkgs=channel:nixos-23.11
    - uses: cachix/cachix-action@v12
      with:
        name: hmenke
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: "(-source$|nixpkgs.tar.gz$)"
    - name: Run nix-build
      run: nix-build --show-trace --no-out-link
    - name: Prepare artifacts
      run: |
        nix-build --show-trace -A local-bin -o .local
        tar cvf local-bin.tar --mode='u+rwX,go+rX' --dereference .local/bin/*
        tar rvf local-bin.tar --mode='u+rwX,go+rX' .local/libexec/git-core/*
        gzip --rsyncable local-bin.tar
    - uses: actions/upload-artifact@v3
      with:
        name: local-bin
        path: local-bin.tar.gz
